do $$
declare v_owner uuid;
begin
  select id into v_owner from auth.users where email = 'mtendler@gmail.com';

  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Cidade Center Norte', 'Sao Paulo', 'Incorporação / imobiliário', null, 'http://www.cidadecenternorte.com.br', 'Located in the north zone of São Paulo, Cidade Center Norte is a multipurpose complex formed by: Shopping Center Norte, a pioneer in the north zone and one of the most complete shopping and living centers in São Paulo; L', 'Complexo de shopping/negócios em SP, não atua em residencial — fora do escopo do canal de parcerias.');
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Construtora Stéfani', 'Ribeirao Preto', 'Construção', '+55 16 4009-9499', 'http://www.construtorastefani.com.br', 'Bem-vindo a nossa página oficial, onde os seus sonhos encontram um lugar!   Somos #EspecialistaEmLoteamentos há quase 40 anos e estamos presentes em mais de 60 cidades do Sudeste e Centro-Oeste brasileiros.   Somos uma e', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Stefani Nogueira Incorporação e Construção', 'Sao Paulo', 'Engenharia civil', '+55 16 3512-2000', null, 'Exemplo de qualidade, seriedade e inovação no mercado da construção civil, a Stéfani Nogueira Incorporação e Construção transporta em cada empreendimento o futuro para o hoje.  Oferece sempre excelência técnica, valoriza', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'AUTÔNOMO', 'Divinesia', 'Incorporação / imobiliário', null, 'http://www.supermoradas.com', 'AUTÔNOMO is a real estate company based in Divinésia, Minas Gerais, Brazil, operating under the brand SuperMoradas.com. Founded in 2000, the company focuses on simplifying property-related processes for its clients. It o', 'Cadastro no Apollo sem nome de empresa (marca SuperMoradas.com), sediada em Divinésia/MG — fora da região Ribeirão Preto.');
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Bueno Netto', 'State of Sao Paulo', 'Construção', null, 'http://www.buenonetto.com.br', 'O grupo Bueno Netto está presente na história brasileira da construção civil há 40 anos e conta com mais de 2.000.000 m2 em desenvolvimento. Com uma trajetória marcada por excelência e credibilidade, hoje, o grupo atua e', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Fernandez Mera Negócios Imobiliários', 'Sao Paulo', 'Incorporação / imobiliário', '+55 11 3066-1005', 'http://www.fmera.com.br', 'Fernandez Mera Negócios Imobiliários Ltda is a prominent real estate brokerage based in São Paulo, Brazil, founded in 1983 by Elbio Fernandez Mera. The company is recognized as one of the largest in the state, specializi', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Habiarte Incorporação e Construção', 'Ribeirao Preto', 'Incorporação / imobiliário', '+55 16 99629-4545', 'http://www.habiarte.com', 'Habiarte Incorporação e Construção is a private real estate development and construction company based in Ribeirão Preto, São Paulo. Established in 1985, the company has built a strong reputation in the high-end market o', 'Já mapeada na aba ''Imobiliárias'' como incorporadora de alto padrão (contato não localizado lá); telefone e site confirmados aqui.');
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'J. Mendes', 'Minas Gerais', 'Mineração e metais', '+55 37 3249-9000', 'http://www.jmendes.com.br', 'J. Mendes, officially known as Grupo J. Mendes, is a Brazilian corporate group based in Itaúna, Minas Gerais, with additional operations in Ouro Preto, Nova Lima, and an international office in New York, USA. Founded in ', 'Grupo de mineração e metais sediado em Minas Gerais — não é player imobiliário, entrou na lista por erro de categorização do Apollo.');
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Grupo QuintoAndar', 'Sao Paulo', 'Incorporação / imobiliário', null, 'http://www.grupoquintoandar.com', 'Grupo QuintoAndar is the largest real estate ecosystem in Latin America, based in Brazil. The company aims to help people "love where they live" by providing a comprehensive range of housing solutions, including searchin', 'Marketplace nacional, não é imobiliária local — fora do escopo de canal regional.');
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Stéfani Nogueira Urbanização, Incorporação e Construção', 'Ribeirao Preto', 'Incorporação / imobiliário', '+55 16 3512-2000', 'http://www.stefaninogueira.com', 'Há mais de 40 anos, somos referência em empreendimentos imobiliários de alto padrão. Reconhecemos nossa inovação, qualidade e segurança. Escolher um imóvel conosco significa obter transparência, comprometimento e sustent', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Pafil Empreendimentos', 'Ribeirao Preto', 'Construção', '+55 16 3602-8282', 'http://www.pafil.com.br', 'Com 25 anos de atuação, a Pafil Empreendimentos nasceu do sonho de dois empreendedores que acreditam no poder transformador da construção civil. Desde então, crescemos com propósito de concretizar o sonho do imóvel própr', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Mundo Apto', 'Sao Paulo', 'Construção', '+55 11 4040-2142', 'http://www.mundoapto.com.br', 'Mundo Apto is a Brazilian real estate development and construction company based in São Paulo, founded in 2017. It specializes in affordable housing and economic segment residential projects. As a joint venture between G', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, '360 Suítes', 'Sao Paulo', 'Incorporação / imobiliário', '+55 11 96171-8008', 'http://www.360suites.com.br', '360 Suítes is a Brazilian company based in São Paulo, founded in 2019. It specializes in the rental and management of furnished apartments for short and long stays, catering to both individuals seeking temporary housing ', 'É a marca coirmã do empreendimento PINA1875 da própria Chaincorp (PINA1875 by 360 Suítes) — não é prospect de canal, já está dentro do ecossistema Chaincorp.');
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'brio Incorporadora', 'Ribeirao Preto', 'Incorporação / imobiliário', null, 'http://www.brioincorporadora.com.br', 'Fundada em maio de 2014, a brio Incorporadora foi criada com o objetivo de idealizar, projetar e entregar produtos de alto valor agregado. O nome da empresa reflete os valores e a forma de trabalho de nossos sócios e col', 'Incorporadora com produtos MCMV em Ribeirão Preto, já citada durante a pesquisa de imobiliárias populares.');
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'GoodStorage', 'Sao Paulo', 'Armazenagem', '+55 11 2222-1220', 'http://www.goodstorage.com.br', 'A maior empresa de armazenamento do Brasil. Somos especialistas em espaços inteligentes que proporcionam mais qualidade de vida para pessoas e mais eficiência para negócios.  Com unidades localizadas nos bairros mais est', 'Empresa de self storage em SP — não é player imobiliário residencial.');
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Vitta Residencial', 'Ribeirao Preto', 'Construção', '+55 800 761 7102', 'http://www.vittaresidencial.com.br', 'Há 15 anos, a Vitta Residencial transforma vidas e cidades, tornando possível a conquista do primeiro imóvel para milhares de famílias. Somos especialistas em moradias acessíveis, seguras e confortáveis, com infraestrutu', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Construtora Pagano', 'Ribeirao Preto', 'Construção', null, 'http://www.construtorapagano.com.br', 'Construtora Pagano is a Brazilian construction and real estate development company founded in 1984 and based in Ribeirão Preto, São Paulo. With over 38 years of experience, the company has successfully delivered more tha', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Copema Engenharia e Construções', 'Ribeirao Preto', 'Construção', '+55 19 3324-5849', 'http://www.copema.com.br', 'A Copema tem o privilégio de transformar sonhos em realidade, construindo lares e ambientes empresariais que definem a paisagem de Ribeirão Preto e Campinas.   Desde 1985, já entregamos mais de 6 mil imóveis que refletem', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Dabi Business Park', 'Ribeirao Preto', 'Incorporação / imobiliário', null, 'http://www.dabibusinesspark.com.br', 'Unimos tecnologia e relações humanas.  Nosso compromisso de conectar empresas e ideias, promover inovação e de fazer parte da vida das pessoas, extrapola os atributos de um Business Park.   Somos uma comunidade de empres', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Smart Construtora e Incorporadora', 'State of Sao Paulo', 'Construção', '+55 11 4040-0442', 'http://www.smartincorporadora.com.br', 'Empresa especializada em construção de edifícios.', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Urben Construtora e Incorporadora', 'Ribeirao Preto', 'Construção', '+55 16 3515-2200', 'http://www.urben.com.br', 'Urben Construtora e Incorporadora Ltda is a mid-sized construction and real estate development company based in Ribeirão Preto, São Paulo, Brazil. Founded on May 16, 2011, Urben focuses on delivering high-quality and sus', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Perplan Incorporação', 'Ribeirao Preto', 'Incorporação / imobiliário', '+55 16 3604-0330', 'http://www.perplan.com.br', 'Perplan Incorporação is a real estate development company located in Ribeirão Preto, São Paulo, Brazil. Established in 2000, it emerged from the merger of two enterprises with over 25 years of combined experience in the ', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Bild Desenvolvimento Imobiliário', 'Ribeirao Preto', 'Construção', '+55 16 3323-9999', 'http://www.bild.com.br', 'Em 2007, quando começamos essa história em Ribeirão Preto - São Paulo, já imaginávamos que, em algum momento,  teríamos orgulho em relembrar tudo o que nos trouxe até aqui.  E cá estamos.  Expandimos nossa atuação para m', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'Construtora Egydio dos Santos', 'Ribeirao Preto', 'Construção', '+55 16 3441-8807', 'http://www.egydiodossantos.com.br', 'Construtora Egydio dos Santos is a well-established real estate development and construction company located in Ribeirão Preto, São Paulo. Founded in 1980 by Ary Egydio dos Santos, the company has over 44 years of experi', null);
  insert into pc_construtoras_prospeccao (owner_id, empresa, cidade, segmento, telefone, site, descricao, observacao)
  values (v_owner, 'JF Bricks Empreendimentos', 'Bebedouro', 'Construção', '+55 17 3340-3673', 'http://www.jfbricks.com.br', 'Com mais de uma década de excelência em incorporação e construção, temos um forte compromisso com a inovação, a sustentabilidade e a alta qualidade em todos os nossos projetos.  Além de excelentes investimentos, concreti', null);
end $$;